development:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: fintrack_development

test:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: fintrack_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: fintrack_production
